[package]
name = "wgpu_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1"
winit = "0.30"
pollster = "0.4"
env_logger = "0.11"
log = "0.4"
bytemuck = { version = "1.19", features = ["derive"] }
egui = "0.29"
egui-wgpu = "0.29"
egui-winit = "0.29"
