[package]
name = "wgpu_playground_examples"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Examples for wgpu_playground"

[dependencies]
wgpu_playground_core = { path = "../wgpu_playground_core" }
wgpu = "22.1"
pollster = "0.4"
env_logger = "0.11"
log = "0.4"
